language: node_js
node_js:
    - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_install:
   - export CHROME_BIN=chromium-browser
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
before_script:
   - npm install
   - bower install